title: Pranav Gajera
logo: /assets/img/pranav.png
description: text below image
# show_downloads: true
# theme: jekyll-theme-minimal
# theme : jekyll-theme-cayman
# theme : jekyll-theme-arnica
theme : jekyll-theme-beautiful-jekyll
